services:
  rtsp-reader:
    image: rtsp-reader:v1.0.1
    container_name: rtsp-reader

    environment:
      - RUNNING_IN_DOCKER=true

    restart: unless-stopped

    volumes:
      - ./logs:/app/logs
      - ./snapshots:/app/snapshots

    stdin_open: true
    tty: true